# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: git_presenter 1.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "git_presenter"
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Colin Gemmell"]
  s.date = "2014-07-09"
  s.description = "Code presentation tool using git"
  s.email = "pythonandchips@gmail.com"
  s.executables = ["git-presenter"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "bin/git-presenter",
    "git_presenter.gemspec",
    "lib/git_presenter.rb",
    "lib/git_presenter/controller.rb",
    "lib/git_presenter/presentation.rb",
    "lib/git_presenter/shell.rb",
    "lib/git_presenter/slide.rb",
    "spec/bugs/max_10_commits_being_parsed_spec.rb",
    "spec/integration/initialize_presentation_spec.rb",
    "spec/integration/moving_through_presentation_spec.rb",
    "spec/integration/start_presentation_spec.rb",
    "spec/integration/update_presentation_spec.rb",
    "spec/lib/git_presenter/controller_spec.rb",
    "spec/lib/git_presenter/presentation_spec.rb",
    "spec/lib/git_presenter/slide_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/command_line_helper.rb",
    "spec/support/git_helpers.rb"
  ]
  s.homepage = "http://github.com/pythonandchips/git-presenter"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Code presentation tool using git"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<git>, [">= 0"])
      s.add_runtime_dependency(%q<launchy>, ["~> 2.1"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.7"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
    else
      s.add_dependency(%q<git>, [">= 0"])
      s.add_dependency(%q<launchy>, ["~> 2.1"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.7"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
    end
  else
    s.add_dependency(%q<git>, [">= 0"])
    s.add_dependency(%q<launchy>, ["~> 2.1"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.7"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
  end
end

